luckyframework/lucky_record

- spec/lucky_record/string_criteria_spec.cr
- src/lucky_record/types.cr
- src/lucky_record/where.cr
> Add string specific criteria methods

- spec/lucky_record/form_spec.cr
- spec/lucky_record/query_spec.cr
- src/lucky_record/model.cr
- src/lucky_record/query.cr
> Add .update with block

- spec/form_spec.cr
- src/lucky_record/form.cr
> Generate the correct form name

- spec/model_spec.cr
- spec/query_builder_spec.cr
- spec/query_spec.cr
- src/lucky_record/criteria/base.cr
- src/lucky_record/query_builder.cr
- src/lucky_record/queryable.cr
> Add order_by to query and query_builder

- spec/form_callbacks_spec.cr
- spec/form_spec.cr
- spec/spec_helper.cr
- src/lucky_record/base_form_template.cr
- src/lucky_record/form.cr
> Add form callbacks

- spec/form_needs_spec.cr
- src/lucky_record/base_form_template.cr
- src/lucky_record/form.cr
- src/lucky_record/needy_initializer.cr
Closes #48
Still need to make it so you can add a needs for just save and update. That can be a separate issue
> Add form needs

- spec/support/comment.cr
- spec/support/post.cr
- src/lucky_record/associations.cr
> Use type declaration for associations

- README.md
It wasn't immediatly clear that I needed a database to run the tests or how to set it up. I thought this could be helpful for anyone else trying to contribute.
> Add testing section to the Readme

- spec/query_spec.cr
- src/lucky_record/errors.cr
- src/lucky_record/queryable.cr
I took ActiveRecord's RecordNotFound Error as example for this PR. If you have any suggestions, tell me.
> Raises RecordNotFound in find query if no record is found

- spec/allow_virtual_spec.cr
- src/lucky_record/allow_virtual.cr
> Require type when setting allow_virtual

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This adds CODE_OF_CONDUCT and CONTRIBUTING documents. I grabbed them from lucky_web.
> Community documents

- spec/allow_virtual_spec.cr
- spec/form_needs_spec.cr
- src/lucky_record/allow_virtual.cr
- src/lucky_record/needy_initializer.cr
> Cleanup allow_virtual and only require needs on save/update

- spec/validations_spec.cr
- src/lucky_record/validations.cr
> Fix typo in vaidate_inclusion_of

- spec/form_needs_spec.cr
- src/lucky_record/needy_initializer.cr
> Add `on` option to form needs

- spec/form_needs_spec.cr
- spec/form_spec.cr
- src/lucky_record/needy_initializer.cr
> Rename Form.save to Form.create

- spec/validations_spec.cr
- src/lucky_record/validations.cr
Closes #84
Makes it more clear what is going on, is a regular method so it's easier
to understand, and I think it reads a bit better too.
> Change validate_confirmation_of to regular method

- spec/virtual_form_spec.cr
- src/lucky_record/params.cr
- src/lucky_record/virtual_form.cr
Closes #55
See #55 for an example
> Virtual forms

- spec/allow_virtual_spec.cr
- spec/virtual_form_spec.cr
- src/lucky_record/allow_virtual.cr
- src/lucky_record/form.cr
- src/lucky_record/virtual_form.cr
> Add VirtualForm#valid? and include virtual fields in Form#fields?

- spec/query_builder_spec.cr
- spec/query_spec.cr
- src/lucky_record/query_builder.cr
- src/lucky_record/queryable.cr
> Add Queryable#offset

- spec/model_spec.cr
- spec/query_builder_spec.cr
- spec/query_spec.cr
- src/lucky_record/query_builder.cr
> Fix chaining with limit

- spec/query_spec.cr
- src/lucky_record/query_builder.cr
- src/lucky_record/queryable.cr
Closes #129
Count will still not work if you try to use limit/offset with it, but I
think that is probably pretty rare. It does work when using order by and
where's though, which is fairly common practice.
Will tackle allowing limit/offset in a separate PR.
> Make count chainable

- spec/spec_helper.cr
- src/lucky_record/repo.cr
Closes #41
This is really slow so it should eventually use a transaction to start
and rollback changes, but this is a simple place to start.
> Add database truncate

- shard.yml
- src/lucky_record/version.cr
Includes some important bug fixes
> Bump version to 0.3.1

- spec/field_spec.cr
- spec/form_spec.cr
- src/lucky_record/field.cr
> Return nil when value is a blank string

- spec/query_builder_spec.cr
- spec/query_spec.cr
- src/lucky_record/query_builder.cr
- src/lucky_record/queryable.cr
Reverses the existing order and returns the last value. If there is no
order clause, orders by the id.
Resolves: #153
> Add Queryable#last

- spec/associations_spec.cr
- spec/query_spec.cr
- spec/support/boxes/user_box.cr
- src/lucky_record/box.cr
Change `LuckyRecord::Box` to return `self`, so setters can be chainable.
> Use UserBox instead of custom factory method

- spec/validations_spec.cr
- src/lucky_record/validations.cr
> Less restricted type for validate_acceptance_of

- spec/query_spec.cr
- src/lucky_record/errors.cr
- src/lucky_record/query_builder.cr
> Raise helpful error when count is used with offset or limit

- spec/form_spec.cr
- spec/preloading_spec.cr
- src/lucky_record/associations.cr
- src/lucky_record/errors.cr
- src/lucky_record/form.cr
- src/lucky_record/queryable.cr
- src/lucky_record/repo.cr
> Preload associations

- db/migrations/20180102171226_add_published_at_to_posts.cr
- shard.yml
- spec/form_spec.cr
- spec/query_builder_spec.cr
- spec/query_spec.cr
- spec/support/post.cr
- src/lucky_record/form.cr
- src/lucky_record/postgres_url.cr
- src/lucky_record/query_builder.cr
- tasks.cr
> Fix nilable fields

- db/migrations/20180102195309_add_non_model_field_to_users.cr
- src/lucky_record/form.cr
- src/lucky_record/insert.cr
- src/lucky_record/query_builder.cr
> Return only known fields when inserting/updating

- spec/form_spec.cr
- src/lucky_record/errors.cr
- src/lucky_record/form.cr
> Cleanup some method names

- spec/form_spec.cr
- src/lucky_record/charms/time_extensions.cr
- src/lucky_record/form.cr
> Parse times as UTC

- shard.yml
- spec/form_spec.cr
- spec/transaction_spec.cr
- src/lucky_record/errors.cr
- src/lucky_record/form.cr
- src/lucky_record/repo.cr
> Transaction support

- spec/form_spec.cr
- src/lucky_record/needy_initializer.cr
> Add save/update without params

- spec/form_needs_spec.cr
- src/lucky_record/needy_initializer.cr
> Change 'needs' to allowed :save option

- spec/query_spec.cr
- src/lucky_record/queryable.cr
> Add Queryable class methods for find, first and last

- db/migrations/20180115194734_create_taggings.cr
- spec/associations_spec.cr
- spec/preloading_spec.cr
- spec/query_builder_spec.cr
- spec/query_spec.cr
- spec/support/base_box.cr
- spec/support/boxes/tag_box.cr
- spec/support/boxes/tagging_box.cr
- spec/support/post.cr
- spec/support/tag.cr
- spec/support/tagging.cr
- src/lucky_record/associations.cr
- src/lucky_record/query_builder.cr
- src/lucky_record/queryable.cr
> Has many through and Queryable#distinct

- spec/validations_spec.cr
- src/lucky_record/errors.cr
- src/lucky_record/validations.cr
One of two validations requested in #112
> Add size validation

- spec/form_needs_spec.cr
- spec/form_spec.cr
- spec/model_spec.cr
- spec/spec_helper.cr
- src/lucky_record/form.cr
- src/lucky_record/needy_initializer.cr
- src/lucky_record/needy_initializer_and_save_methods.cr
- src/lucky_record/params.cr
Also does quite a bit of cleanup in macros
> Pass params in create/updates

- src/lucky_record/associations.cr
- src/lucky_record/form.cr
> Improve some error messages

- spec/lazy_loading_spec.cr
- spec/preloading_spec.cr
- spec/support/lazy_load_helpers.cr
- src/lucky_record/associations.cr
> Allow lazy loading associations

- spec/associations_spec.cr
- spec/form_callbacks_spec.cr
- spec/form_needs_spec.cr
- spec/form_spec.cr
- spec/lazy_loading_spec.cr
- spec/model_spec.cr
- spec/preloading_spec.cr
- spec/query_associations_spec.cr
- spec/query_spec.cr
- spec/transaction_spec.cr
- spec/validations_spec.cr
- src/lucky_record/box.cr
> Rename Box.save -> Box.create

- spec/preloading_spec.cr
- src/lucky_record/box.cr
> Box.create with a block

- spec/type_extension_spec.cr
- src/lucky_record/box.cr
Closes #239
Much better error messages now
> Delegate fields in forms

- spec/query_builder_spec.cr
- spec/query_spec.cr
- spec/transaction_spec.cr
- src/lucky_record/criteria.cr
- src/lucky_record/query_builder.cr
- src/lucky_record/queryable.cr
> Add new select aggregate methods

- spec/query_spec.cr
- src/lucky_record/queryable.cr
> Add Queryable#none

- spec/form_spec.cr
- src/lucky_record/form.cr
> Set updated_at during update

- spec/form_spec.cr
- spec/virtual_spec.cr
- src/lucky_record/field.cr
- src/lucky_record/fillable_field.cr
- src/lucky_record/form.cr
- src/lucky_record/validations.cr
- src/lucky_record/virtual.cr
This will make it easier to restrict these types
Closes https://github.com/luckyframework/lucky_record/issues/223
> FillableField is child of Field. Add Fillable module

- spec/form_spec.cr
- spec/virtual_spec.cr
- src/lucky_record/fillable_field.cr
> Remove Fillable module

- spec/query_builder_spec.cr
- spec/query_spec.cr
- src/lucky_record/criteria.cr
- src/lucky_record/query_builder.cr
- src/lucky_record/queryable.cr
> Add `Queryable#distinct_on`

- db/migrations/20170127143149_create_users.cr
- spec/model_spec.cr
- spec/support/boxes/user_box.cr
- spec/support/user.cr
- src/lucky_record/charms/float64_extensions.cr
This is to allow for Float64? (optional) model fields
I'm still working on trying this out with my project but the build looks fine
> Add Float64::Lucky.parse(value : PG::Numeric) overload

- src/lucky_record/needy_initializer_and_save_methods.cr
> Add better type restrictions for forms

- shard.yml
Part of https://github.com/luckyframework/lucky_cli/pull/281
> Use dots for precompilation
